sudo: false
branches:
  only:
  - master
language: node_js
notifications:
  email:
    on_success: always
    on_failure: change
cache:
  directories:
    - node_modules
node_js:
  - '9'
install:
  - npm install
after_success:
  - npm run build
  - cd dist
  - npm run travis-deploy-once "npm run semantic-release"
