sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: always
    on_failure: change
node_js:
  - '9'
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm run test:cover
after_success:
  - npm run build
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
